project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('vircom/', include('vircom.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

vircom/urls.py
from django.urls import path
from . import views


app_name = 'vircom'
urlpatterns = [
    #VIEWS
    path('', views.index, name='index'),
    path('<str:community_name>/feed', views.community_detail, name='community_detail'),
    path('<str:community_name>/<str:post_id>/edit/', views.edit_post, name='edit_post'),
    path('<str:community_name>/new-data-type', views.new_data_type, name='new_data_type'),
    path('<str:community_name>/new-<str:data_type_id>', views.new_data_type_object, name='new_data_type_object'),
    path('new-community/', views.new_community, name='new_community'),
    path('<str:community_name>/<str:data_type_id>/edit', views.edit_data_type, name='edit_data_type'),
    path('sign-up/', views.sign_up, name='sign_up'),
    path('log-in/', views.log_in, name='log_in'),
    
    #REQUESTS
    path('<str:community_id>/<str:post_id>/delete-post/', views.delete_post, name='delete_post'),
    path('<str:community_id>/<str:post_id>/change-post/', views.change_post, name='change_post'),
    path('<str:community_id>/create-data-type/', views.create_data_type, name='create_data_type'),
    path('<str:community_id>/<str:data_type_id>/create-data-type-object', views.create_data_type_object, name='create_data_type_object'),
    path('create-community/', views.create_community, name='create_community'),
    path('<str:community_id>/<str:data_type_id>/change-data-type', views.change_data_type, name='change_data_type'),
    path('<str:community_id>/<str:data_type_id>/delete-data-type', views.delete_data_type, name='delete_data_type'),
    path('create-user/', views.create_user, name='create_user'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('log-out/', views.log_out, name='log_out'),
    path('<str:community_id>/join', views.join_community, name='join_community'),
    path('<str:community_id>/unsubscribe', views.unsubscribe_community, name='unsubscribe_community'),
    path('<str:community_id>/<str:data_type_id>/search', views.advanced_search, name='advanced_search'),
    path('community-search/', views.search_community, name='search_community'),
]

vircom/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import uuid
import datetime
from django.contrib.postgres.fields import ArrayField, JSONField
from django.contrib.auth.models import User

# Create your models here.
class Community(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank = True)
    tags = JSONField()
    pub_date = models.DateTimeField('date published')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self):
        return self.name       

class DataType(models.Model):   
    name = models.CharField(max_length=200)
    community = models.ForeignKey(Community, on_delete=models.PROTECT)
    fields = JSONField()
    is_archived = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self):
        return self.community.name + "-" + self.name   

class DataTypeObject(models.Model):
    data_type = models.ForeignKey(DataType, on_delete=models.PROTECT)
    fields = JSONField()
    pub_date = models.DateTimeField('date published')
    community = models.ForeignKey(Community, on_delete=models.PROTECT) 
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    tags = JSONField()
    def __str__(self):
        return self.community.name + "-" + self.data_type.name + "-" + str(self.pk) 

class MediaFile(models.Model):
    upload = models.FileField(upload_to='uploads')
    url = models.TextField(blank = True)
    def __str__(self):
        return str(self.upload)

class VircomUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    joined_communities = ArrayField(models.IntegerField(), blank=True, null=True)
    #data_types = ArrayField(models.IntegerField())
    #posts = ArrayField(models.IntegerField())
    def __str__(self):
        return self.user.username  


    

vircom/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .models import Community, DataType, DataTypeObject, MediaFile, VircomUser
from django.http import Http404
from django.urls import reverse
import datetime
import json
import uuid
from django.core import serializers
from django.http import JsonResponse
from django.core.files import File
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import requests

# HOMEPAGE

def index(request):
    community_list = Community.objects.order_by('-pub_date')[:30]
    if not request.user.is_authenticated:
        context = {
            'community_list': community_list,
        }
    else:
        vircom_user = get_object_or_404(VircomUser, user=request.user)
        context = {
            'community_list': community_list,
            'user': vircom_user
        }
    return render(request, 'vircom/index.html', context)

# SEARCH COMMUNITY

def search_community(request):
    search_term = str(request.POST.get('search_term', "")).strip()
    if search_term == "":
        community_list = Community.objects.order_by('-pub_date')[:30]
        search_result = None
    else:
        community_list = Community.objects.filter(name__icontains=search_term).order_by('-pub_date')
        search_result = str(len(community_list)) + " communities matched your search query."
    if not request.user.is_authenticated:
        context = {
            'community_list': community_list,
            'search_result': search_result
        }
    else:
        vircom_user = get_object_or_404(VircomUser, user=request.user)
        context = {
            'community_list': community_list,
            'user': vircom_user,
            'search_result': search_result
        }
    return render(request, 'vircom/index.html', context)
    

# NEW COMMUNITY    

def new_community(request):    
    if not request.user.is_authenticated:
        community_list = Community.objects.order_by('-pub_date')[:30]
        return render(request, 'vircom/index.html', {
            'community_list': community_list,
            'error_message': "You need to Log in or Sign up to create new community.",
        })
    else:   
        vircom_user = get_object_or_404(VircomUser, user=request.user)
        return render(request, 'vircom/new_community.html', {'user': vircom_user})


def create_community(request):
    if not request.user.is_authenticated:
        community_list = Community.objects.order_by('-pub_date')[:30]
        return render(request, 'vircom/index.html', {
            'community_list': community_list,
            'error_message': "You need to Log in or Sign up to create new community.",
        }) 
    name = str(request.POST.get('name', "")).strip()
    description = str(request.POST.get('description', "")).strip()
    try:
        old_community = Community.objects.get(name=name)
    except:
        old_community = None
    if old_community:
        return render(request, 'vircom/new_community.html', {
            'error_message': "There is another community named " + name,
            'description': description
        })
    if "cancel" in request.POST:
        return HttpResponseRedirect(reverse('vircom:index'))
    if "get_tag" in request.POST:
        if name == "":
            return render(request, 'vircom/new_community.html', {
            'error_message': "You need to enter community name to get tag suggestions.",
            'tags': suggested_tag_list,
            'description': description
        })
        else:
            suggested_tags = suggest_tags(name)
            suggested_tag_list = ""
            if suggested_tags:
                for item in suggested_tags["items"]:
                    suggested_tag_list = suggested_tag_list + item["label"] + ","
                suggested_tag_list = suggested_tag_list[:-1]
            return render(request, 'vircom/new_community.html', {
                'community_name': name,
                'tags': suggested_tag_list,
                'description': description
            })
    community = Community(name=name, description=description, pub_date=datetime.datetime.now(), tags={}, user=request.user)
    if community.name == "" or community.description == "" or request.POST['tags'] == "":
        return render(request, 'vircom/new_community.html', {
            'community': community,
            'error_message': "Name, Description or Tag fields cannot be empty.",
            'description': description
        })
    else:
        tags_dict = get_post_tags(request.POST['tags'])
        if tags_dict:
            tags = tags_dict
        else: 
            tags = {}    
        community.tags = tags
        fields = {}
        fields['fields'] = [{
                "name": "Title",
                "field_id": "1",
                "field_type": "Text",
                "required": "Yes",
                "enumerated": "No",
                "multi_choice": "off",
                "options": []
            },
            {
                "name": "Description",
                "field_id": "2",
                "field_type": "Long Text",
                "required": "Yes",
                "enumerated": "No",
                "multi_choice": "off",
                "options": []
            }
        ]
        community.save()
        post = DataType(name="Generic Post", community=community, fields=fields, user=request.user)
        post.save()
        vircom_user = get_object_or_404(VircomUser, user=request.user)
        vircom_user.joined_communities.append(community.pk)
        vircom_user.save()
        return HttpResponseRedirect(reverse('vircom:community_detail', args=(community.name,)))

# GET WIKIDATA TAGS

def suggest_tags(community_name):
    wiki_items = {}
    wiki_items["items"] = get_wiki_data_items(community_name, 10)
    tags = {}
    tags["items"] = []
    if wiki_items["items"] == []:
        return None
    counter = 0
    deleted_keys = []
    for item in wiki_items['items']: 
        if counter != 0:
            for i in range(0,counter):
                print(str(item["label"]).lower() + "    " + str(wiki_items["items"][i]["label"]).lower())
                if str(item["label"]).lower() == str(wiki_items["items"][i]["label"]).lower():
                    print("true")
                    deleted_keys.append(item)
                    break
        counter = counter + 1 
    for key in deleted_keys:
        wiki_items["items"].remove(key)                  
    return wiki_items

def get_wiki_data_items(search_term, limit):
    url = "https://www.wikidata.org/w/api.php"
    params = {
    "action": "wbsearchentities",
    "format": "json",
    "language": "en",
    "limit": limit,
    "search": search_term
    }
    response = requests.get(url=url, params=params)
    data = response.json()
    return data["search"]


# JOIN COMMUNITY        

def join_community(request, community_id):
    community = get_object_or_404(Community, pk=community_id)
    data_type_list = DataType.objects.filter(community=community).order_by('pk')
    data_type_object_list = DataTypeObject.objects.filter(community=community).order_by('-pub_date')
    context = {
            'user': request.user,
            'community': community,
            'data_type_list':  data_type_list,
            'data_type_object_list': data_type_object_list,
    }
    if not request.user.is_authenticated:
        context["error_message"] = "You need to Log in or Sign up to join a community."
        return render(request, 'vircom/community_detail.html', context)
    vircom_user = get_object_or_404(VircomUser, user=request.user)
    if vircom_user.joined_communities:
        if community.pk in vircom_user.joined_communities:
            context["joined"] = True
            context["error_message"] = "You are already a member of " + community.name + "."
            return render(request, 'vircom/community_detail.html', context)
    vircom_user.joined_communities.append(community.pk)
    vircom_user.save()
    return HttpResponseRedirect(reverse('vircom:community_detail', args=(community.name,)))

# UNSUBSCRIBE COMMUNITY

def unsubscribe_community(request, community_id):
    community = get_object_or_404(Community, pk=community_id)
    data_type_list = DataType.objects.filter(community=community).order_by('pk')
    data_type_object_list = DataTypeObject.objects.filter(community=community).order_by('-pub_date')
    context = {
            'community': community,
            'data_type_list':  data_type_list,
            'data_type_object_list': data_type_object_list,
    }
    if not request.user.is_authenticated:    
        return render(request, 'vircom/community_detail.html', context)
    vircom_user = get_object_or_404(VircomUser, user=request.user)
    context["user"] = vircom_user  
    if community.pk not in vircom_user.joined_communities:
        context["error_message"] = "You are not a member of " + community.name + "."
        return render(request, 'vircom/community_detail.html', context)
    else:
        vircom_user.joined_communities.remove(community.pk)
        vircom_user.save()
        return HttpResponseRedirect(reverse('vircom:community_detail', args=(community.name,)))

# COMMUNITY DETAIL    

def community_detail(request, community_name):
    community = get_object_or_404(Community, name=community_name)
    data_type_list = DataType.objects.filter(community=community).order_by('pk')
    data_type_object_list = DataTypeObject.objects.filter(community=community).order_by('-pub_date')
    context = {
        'community': community,
        'data_type_list':  data_type_list,
        'data_type_object_list': data_type_object_list,
    }
    if not request.user.is_authenticated:
        return render(request, 'vircom/community_detail.html', context)
    else:

vircom/templates/vircom/index.html
<!DOCTYPE html>
<html>

<head>
  <!--    Load Bootstrap via CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  {% load static %}
  <link href="{% static 'vircom/css/text_boxes.css' %}" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>

<body>
  <!--    NAVBAR -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'vircom:index' %}">VirCom</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'vircom:index' %}">Home<span class="sr-only">(current)</span></a>
        </li>
        {% if user.user %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vircom:new_community'%}">New Community</a>
        </li>
        {% endif %}
      </ul>
      <div style="float: right;">
        <form class="form-inline my-2 my-lg-0" action="{% url 'vircom:search_community' %}" method="post">
          {% csrf_token %}
          <input style="width: 250px;" class="form-control mr-sm-2" type="search" placeholder="Search Community"
            aria-label="Search Community" name="search_term">
          <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
      <ul class="navbar-nav" style="float: right;">
        {% if user.user %}
        <li class="nav-item">
          <a class="nav-link disabled">Hi, {{user.user.username}}!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vircom:log_out'%}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vircom:log_in'%}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vircom:sign_up'%}">Sign Up</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <!--    NAVBAR -->
  <br /><br /><br /><br />
  <div class="container" style="width: 800px; margin:0 auto;">
  {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>
  {% endif %}
  {% if search_result %}<p style="color: blue"><strong>{{ search_result }}</strong></p>
  {% endif %}

  <!--    COMMUNITY LIST -->
    {% if community_list %}
    <ul class="list-group">
      {% for community in community_list %}
      <li class="list-group-item"><a href="{% url 'vircom:community_detail' community.name %}">{{ community.name}}</a>
      </li>
      <li class="list-group-item">{{community.description}}</li>
      <li class="list-group-item">
        <div class="input-group">{% for tag in community.tags.tags%}<p class="WikiItemTag">{{tag.tag}}<span
              class="textboxwWikiInfo"><a href="{{tag.url}}"
                style="color:#FFFF;">{{tag.qid}}-{{tag.label}}<br />{{tag.description}}</a></span></p>
          &nbsp;&nbsp;&nbsp;&nbsp;{% endfor %}</div>
      </li>
      <br />
      {% endfor %}
    </ul>
    {% else %}
    <p>No communities are available.</p>
    {% endif %}
  </div>
  <br /><br />
  <!--    COMMUNITY LIST -->

  <!--    FOOTER -->
  <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light" style="height: 25px;"></nav>
  <!--    FOOTER -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

vircom/templates/vircom/login.html
<!DOCTYPE html>
<html>

<head>

    <!--    Load Bootstrap via CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    {% load static %}
    <script src="{% static 'vircom/js/data_type.js' %}"></script>
    <link href="{% static 'vircom/css/text_boxes.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>
    <!--    NAVBAR -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'vircom:index' %}">VirCom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'vircom:index' %}">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav" style="float: right;">
                {% if user.user.username %}
                <li class="nav-item">
                    <a class="nav-link disabled">Hi, {{user.user.username}}!</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:log_out'%}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:log_in'%}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:sign_up'%}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--    NAVBAR -->
    <br /><br /><br /><br />

    <div class="container" style="width: 800px; margin:0 auto;">

    <h3>Log in to Vircom</h3>
    {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'vircom:authenticate_user' %}" method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="InputUserName">Username or Mail Adress</label>
            <input type="text" class="form-control" id="InputUserName" aria-describedby="InputUserName"
                placeholder="Enter your username or email adress" name="user_key">
        </div>
        <div class="form-group">
            <label for="InputPassword">Password</label>
            <input type="password" class="form-control" id="Password" aria-describedby="Password"
                placeholder="Enter your password" name="password">
        </div>
        
        <div class="input-group-btn">
            <button type="submit" class="btn btn-outline-success">Log in</button>
            <button class="btn btn-outline-danger" type="submit" name="cancel" value="cancel"
                style="margin-left: 10px;">Cancel</button>

        </div>
    </form>


</br></br>

<!--    FOOTER -->
<nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light" style="height: 25px;"></nav>
<!--    FOOTER -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
    crossorigin="anonymous"></script>
</body>

</html>

vircom/templates/vircom/new_community.html
<!DOCTYPE html>
<html>

<head>
    <!--    Load Bootstrap via CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% load static %}
    <link href="{% static 'vircom/css/text_boxes.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>

<body>
    <!--    NAVBAR -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'vircom:index' %}">VirCom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:index' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'vircom:new_community'%}">New Community<span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav" style="float: right;">
                {% if user.user.username %}
                <li class="nav-item">
                    <a class="nav-link disabled">Hi, {{user.user.username}}!</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:log_out'%}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:log_in'%}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vircom:sign_up'%}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--    NAVBAR -->
    <br /><br /><br /><br />

    <div class="container" style="width: 800px; margin:0 auto;">
        <h3>Create a new community</h3>
        {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}

        <!--    FORM -->
        <form action="{% url 'vircom:create_community'%}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="CommunityName">Community Name</label>
                {% if community_name %}
                <input type="text" class="form-control" id="CommunityName" aria-describedby="CommunityName"
                    placeholder="Enter community name" value="{{community_name}}" name="name">
                {% else %}
                <input type="text" class="form-control" id="CommunityName" aria-describedby="CommunityName"
                    placeholder="Enter community name" name="name">
                {% endif %}
            </div>
            <div class="form-group">
                <label for="CommunityDescription">Description</label>
                {% if description %}
                <textarea class="form-control" id="CommunityDescription" placeholder="Briefly describe your community"
                    rows="5" name="description"></textarea>
                {% else %}
                <textarea class="form-control" id="CommunityDescription" placeholder="Briefly describe your community"
                    rows="5" name="description"></textarea>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="CommunityDescription">Tags</label>
                {% if tags %}
                <input type="text" class="form-control" data-role="tagsinput" value="{{tags}}" name="tags" />
                {% else %}
                <input type="text" class="form-control" data-role="tagsinput" name="tags" />
                {% endif %}
                <small id="CommunityTagsHelper" class="form-text text-muted">You can seperate the tags using comma(,).
                    e.g
                    tag1,tag2,tag3...</small>
            </div>
            <div class="input-group-btn">
                <button type="submit" class="btn btn-outline-success">Create Community</button>
                <button class="btn btn-outline-primary" type="submit" name="get_tag" value="get_tag"
                    style="margin-left: 10px;">Get
                    Tag Suggestions</button>
                <button class="btn btn-outline-danger" type="submit" name="cancel" value="cancel"
                    style="margin-left: 10px;">Cancel</button>
            </div>
        </form>
        <!--    FORM -->
    </div>
    </br>

    <!--    FOOTER -->
    <nav class="navbar fixed-bottom navbar-expand-lg navbar-light bg-light" style="height: 25px;"></nav>
    <!--    FOOTER -->

    {% if description %}
    <script>
        function myFunction() {
            document.getElementById("CommunityDescription").defaultValue = "{{description}}";
        }
    </script>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>